/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'index',
    'features',
    {
      type: 'category',
      label: 'Getting Started',
      items: ['docker', 'kubernetes'],
    },
    'config',
    'upgrading',
    'admin-ui',
    {
      type: 'category',
      label: 'Auth Providers',
      items: ['auth-provider/azure', 'auth-provider/google', 'auth-provider/keycloak'],
    },
    'booking-ui',
    'confluence',
    'rest-api',
    'support',
  ],
};

module.exports = sidebars;
